language: php

php:
  - 8.2
  - 8.3

# faster builds on new travis setup not using sudo
sudo: false

services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction
# setup application:
  - |
    vendor/bin/codecept build -c tests/codeception.yml
before_install:
  - mysql --version

  # initialize databases
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mdm_admin_test;'

script:
  - |
    cd tests/web
    php -S localhost:8080 > /dev/null 2>&1 &
    cd ..
    vendor/bin/codecept run -c tests/codeception.yml